In [1]:
# -*- coding: utf-8 -*-
import pandas as pd
import datetime
from tqdm import *
import numpy as np
from scipy import stats

df=pd.read_csv(r'C:\luyan\paper_code\data\daily.csv')


df['duration']=df.loc[:,'16':'30'].apply(np.sum,axis=1)
df.head(5)

             id      date   16   17   18   19         20  ...        26   27   28   29   30  ac_type   duration
0  0007A88A4D8D  20160728  0.0  0.0  0.0  0.0   0.000000  ...  0.000000  0.0  0.0  0.0  0.0      f_s  11.742698
1  0007A88A4D8D  20160729  0.0  0.0  0.0  0.0   0.000000  ...  5.393542  0.0  0.0  0.0  0.0      f_s  10.584139
2  0007A88A4D8D  20160730  0.0  0.0  0.0  0.0   7.301306  ...  0.000000  0.0  0.0  0.0  0.0      f_s   8.701008
3  0007A88A4D8D  20160801  0.0  0.0  0.0  0.0  15.453603  ...  0.000000  0.0  0.0  0.0  0.0      f_s  15.600466
4  0007A88A4D8D  20160802  0.0  0.0  0.0  0.0   0.000000  ...  0.000000  0.0  0.0  0.0  0.0      f_s  21.252586

[5 rows x 19 columns]

In [2]:
def droplevel(df):
    df.columns=df.columns.droplevel(0)

def aggfeature(df,featurename):
    df_mean=pd.pivot_table(df,values=featurename,index='id',aggfunc=[np.mean])
    droplevel(df_mean)
    df_mean.reset_index(inplace=True)
    df_mean.columns=['id',featurename+'_mean']
    
    df_median=pd.pivot_table(df,values=featurename,index='id',aggfunc=[np.median])
    droplevel(df_median)
    df_median.reset_index(inplace=True)
    df_median.columns=['id',featurename+'_median']
    
    
    df_std=pd.pivot_table(df,values=featurename,index='id',aggfunc=[np.std])
    droplevel(df_std)
    df_std.reset_index(inplace=True)
    df_std.columns=['id',featurename+'_std']
    
    
    
    df_skew=pd.pivot_table(df,values=featurename,index='id',aggfunc=[stats.skew])
    droplevel(df_skew)
    df_skew.reset_index(inplace=True)
    df_skew.columns=['id',featurename+'_skew']
    
    df_kurt=pd.pivot_table(df,values=featurename,index='id',aggfunc=[stats.kurtosis])
    droplevel(df_kurt)
    df_kurt.reset_index(inplace=True)
    df_kurt.columns=['id',featurename+'_kurt']
    
    df_merge=pd.merge(df_mean,df_median,on='id')
    df_merge=pd.merge(df_merge,df_std,on='id')
    df_merge=pd.merge(df_merge,df_skew,on='id')
    df_merge=pd.merge(df_merge,df_kurt,on='id')
    
    return df_merge






df_duration_features=aggfeature(df,'duration')

df_duration_features.head(5)
#df_duration_features.to_csv(r'C:\luyan\paper_code\data\feature_data\daily_duration.csv',index=False)

             id  duration_mean  duration_median  duration_std  duration_skew  duration_kurt
0  0007A88A4D8D      12.594447        13.058577      5.691970       0.107820      -0.924586
1  0007A88B9A54       5.702652         3.561026      5.107522       1.646614       1.745557
2  0007A88B9C97       7.837327         7.230340      5.481980       0.890935       0.439465
3  0007A88BA9B4       8.506129         6.108834      6.884634       0.484943      -1.331898
4  0007A88BCE80      11.632479        10.967803      5.422689       0.534327       0.017156